# Generated by Django 5.0.3 on 2024-04-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('heure_depart', models.DateTimeField()),
                ('heure_arrivee', models.DateTimeField()),
                ('destination', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'On Time'), (2, 'Delayed'), (3, 'Cancelled')], default=1)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
